name: simple_socket
description: A new Flutter package with implemetation socket communication
version: 0.2.2
homepage: https://github.com/PanteoPro/simple_socket_dart

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.22.1
